name: job
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: echo -n "${{ env.TOKEN_BASE64 }}" | base64 --decode > ./test
        env:
          TOKEN_BASE64: ${{secrets.TOKEN_BASE64}}
      - run: chmod 600 ./test
      - run: node key.js
        env:
          TARGET: test