name: job
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: echo -n "${{ env.TOKEN_BASE64 }}" | base64 --decode > ./test
        env:
          TOKEN_BASE64: ${{secrets.TOKEN_BASE64}}
      - run: chmod 600 ./test
      - run: node key.js > current.txt
        env:
          TARGET: test
          BEFORE: ./before.txt
      - run: mv current.txt before.txt
      - uses: actions/upload-artifact@v4
        with:
          name: before
          path: ./before.txt