name: job
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
# artifactはjob間データ共有には使用不可
# https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
# - uses: actions/download-artifact@v4
#   with:
#     name: before
#     path: ./
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: echo -n "${{ env.TOKEN_BASE64 }}" | base64 --decode > ./target
        env:
          TOKEN_BASE64: ${{secrets.TOKEN_BASE64}}
      - run: chmod 600 ./target
      - run: node key.js
        env:
          TARGET: target
          LIST: ./checked.txt
      - run: cat ./checked.txt
      - run: |
          git config user.name "Daiki Arai"
          git config user.email "darai0512@yahoo.co.jp"
          git add ./checked.txt
          git commit -m "update checked list"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
